// Asset loader — loads pre-rendered .kp bitmaps for the web emulator.
//
// Assets are generated by gen-ui-assets.mjs from definitions.yaml.
// The emulator blits these bitmaps exactly like firmware does — no text rendering at runtime.
//
// All assets are 2-bit grayscale (bit_depth=2). No B&W mode.

const cache = new Map()

let _lang = 'en'        // current language code

/**
 * Set the active language for asset loading.
 */
export function setLang(lang) {
  _lang = lang
}

let lz4 = null
async function getLz4() {
  if (!lz4) lz4 = (await import('lz4js')).default
  return lz4
}

/**
 * Unpack a bit plane into per-pixel values (0 or 1).
 */
function unpackPlane(plane, w, h) {
  const rowBytes = Math.ceil(w / 8)
  const pixels = new Uint8Array(w * h)
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const byteIdx = y * rowBytes + (x >> 3)
      const bitMask = 1 << (7 - (x & 7))
      pixels[y * w + x] = (plane[byteIdx] & bitMask) ? 1 : 0
    }
  }
  return pixels
}

/**
 * Decode a .kp file into pixel levels.
 * KP format: [magic:4][w:2][h:2][depth:1][comp:1][dataSize:4][flags:1][reserved:1]
 * Always bit_depth=2 (2-bit grayscale, 4 levels).
 * Data: [lsb_size:4][lsb_data][msb_size:4][msb_data]
 */
async function decodeKp(buffer) {
  const view = new DataView(buffer)
  const w = view.getUint16(4, true)
  const h = view.getUint16(6, true)
  const bitDepth = new Uint8Array(buffer)[8]
  const compression = new Uint8Array(buffer)[9]
  const contentFlags = new Uint8Array(buffer)[14]

  const rowBytes = Math.ceil(w / 8)
  const planeSize = rowBytes * h

  let off = 16

  async function readBlock() {
    const blockSize = view.getUint32(off, true); off += 4
    if (compression) {
      const comp = new Uint8Array(buffer.slice(off, off + blockSize)); off += blockSize
      const lib = await getLz4()
      const out = new Uint8Array(planeSize)
      lib.decompressBlock(comp, out, 0, blockSize, 0)
      return out
    } else {
      const data = new Uint8Array(buffer.slice(off, off + blockSize)); off += blockSize
      return data
    }
  }

  // bit_depth=2: [gs (LSB) first][bw (MSB) second]
  const gsPlane = await readBlock()
  const bwPlane = await readBlock()
  const gsBits = unpackPlane(gsPlane, w, h)
  const bwBits = unpackPlane(bwPlane, w, h)

  const isLandscape = (contentFlags & 0x04) !== 0

  if (isLandscape) {
    // Landscape-packed (pages): rotate back to portrait for browser canvas
    const pw = h, ph = w
    const pixels = new Uint8Array(pw * ph)
    for (let ly = 0; ly < h; ly++) {
      for (let lx = 0; lx < w; lx++) {
        const level = (bwBits[ly * w + lx] << 1) | gsBits[ly * w + lx]
        const px = h - 1 - ly
        const py = lx
        pixels[py * pw + px] = level
      }
    }
    return { w: pw, h: ph, pixels, bitDepth, contentFlags }
  } else {
    // Portrait-packed (UI assets, covers): no rotation needed
    const pixels = new Uint8Array(w * h)
    for (let i = 0; i < w * h; i++) {
      pixels[i] = (bwBits[i] << 1) | gsBits[i]
    }
    return { w, h, pixels, bitDepth, contentFlags }
  }
}

/**
 * Convert pixel levels to RGBA ImageData for canvas blitting.
 * 4 levels: 0=black(0), 1=dark(85), 2=light(170), 3=white(255)
 */
function pixelsToImageData(pixels, w, h) {
  const GRAY = [0, 85, 170, 255]
  const rgba = new Uint8ClampedArray(w * h * 4)
  for (let i = 0; i < w * h; i++) {
    const g = GRAY[pixels[i]]
    rgba[i * 4] = g
    rgba[i * 4 + 1] = g
    rgba[i * 4 + 2] = g
    rgba[i * 4 + 3] = 255
  }
  return new ImageData(rgba, w, h)
}

/**
 * Load a .kp asset file and return decoded bitmap.
 * Results are cached.
 *
 * @param {string} key — asset key e.g. "help.read"
 * @param {string} [lang='en']
 * @returns {Promise<{ w, h, pixels, imageData }>}
 */
export async function loadAsset(key, lang = 'en') {
  const cacheKey = `${lang}/${key}`
  if (cache.has(cacheKey)) return cache.get(cacheKey)

  const url = `${import.meta.env.BASE_URL}assets/${lang}/${key}.kp`
  try {
    const resp = await fetch(url)
    if (!resp.ok) {
      console.warn(`[asset-loader] fetch failed: ${url} (${resp.status})`)
      return null
    }

    const buffer = await resp.arrayBuffer()
    const decoded = await decodeKp(buffer)
    const { w, h, pixels, bitDepth, contentFlags } = decoded

    const imageData = pixelsToImageData(pixels, w, h)

    const result = {
      w, h, pixels, bitDepth, contentFlags,
      imageData,
    }
    cache.set(cacheKey, result)
    return result
  } catch (err) {
    console.error(`[asset-loader] error loading ${key}:`, err)
    return null
  }
}

/**
 * Preload all assets for a given language.
 * Call at app startup to avoid per-frame fetch latency.
 */
export async function preloadAssets(assetKeys, lang = 'en') {
  const results = await Promise.all(assetKeys.map(k => loadAsset(k, lang)))
  const loaded = results.filter(Boolean).length
  console.log(`[asset-loader] preloaded ${loaded}/${assetKeys.length} assets (${lang})`)
  return loaded
}

/**
 * Blit a loaded asset onto a canvas context at (x, y).
 *
 * @param {CanvasRenderingContext2D} ctx
 * @param {{ imageData: ImageData, w: number, h: number }} asset
 * @param {number} x
 * @param {number} y
 */
export function blitAsset(ctx, asset, x, y) {
  if (!asset?.imageData) return
  ctx.putImageData(asset.imageData, x, y)
}

/**
 * Get cached asset (sync, returns null if not loaded yet).
 * Uses module-level language if not specified.
 */
export function getAsset(key, lang) {
  const l = lang || _lang
  return cache.get(`${l}/${key}`) || null
}

/**
 * Clear asset cache.
 */
export function clearCache() {
  cache.clear()
}
